name: CI checks
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Terraform Format Check
        run: |
          terraform fmt -recursive
          if [ -n "$(git diff)" ]; then
            echo "Changes made by terraform fmt"
          else
            echo "No changes made by terraform fmt"
          fi

      - name: Terraform Validation Check
        run: |
           for FOLDER in modules/*; do
            pushd $FOLDER
            terraform init
            terraform validate
            if [ $? -ne 0 ]; then
              echo "Terraform validation failed in $FOLDER"
              popd
              exit 1
            fi
            popd
           done
             
      - name: Terraform linting
        run: |
