name: Terraform flow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment you wish to use
        options:
        - integration
        - staging
        - production
      resource:
        type: choice
        description: Which resource you wish to create
        options:
        - key-vault
        - storage-account

jobs:
  build:
    runs-on: self-hosted
    env:
      WORK_DIR: ${{ inputs.environment }}/${{ inputs.resource }}/

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Azure
        run: 
          |
          if [[ "${{inputs.environment}}" == "integration" || "${{inputs.environment}}" == "staging" ]]; then
            az login --service-principal -u ${{secrets.CLIENT_ID}} -p ${{secrets.CLIENT_SECRET}} --tenant ${{secrets.TENANT_ID}}
          else
            az login --service-principal -u ${{secrets.CLIENT_ID_PROD}} -p ${{secrets.CLIENT_SECRET_PROD}} --tenant ${{secrets.TENANT_ID}}
          fi

      - name: run terraform init
        working-directory: ${{ env.WORK_DIR }}
        run: terraform init

      - name: run terraform plan
        working-directory: ${{ env.WORK_DIR }}
        run: terraform plan

      - name: terraform apply
        working-directory: ${{ env.WORK_DIR }}
        run: terraform apply -auto-approve
