name: Terraform flow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment you wish to use
        options:
        - integration
        - production
      resource:
        type: choice
        description: Which resource you wish to create
        options:
        - key-vault
        - storage-account

permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    env:
      WORK_DIR: ${{ inputs.environment }}/${{ inputs.resource }}/
      # ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      # ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      # ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      # ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}



    steps:
      - uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v1
        with:  
          creds: ${{ inputs.environment == 'integration' && secrets.INTEGRATION_CREDS || secrets.PRODUCTION_CREDS}}

      - name: run terraform init
        working-directory: ${{ env.WORK_DIR }}
        run: terraform init

      - name: run terraform plan
        working-directory: ${{ env.WORK_DIR }}
        run: terraform plan

      - name: terraform apply
        working-directory: ${{ env.WORK_DIR }}
        run: terraform apply -auto-approve